import minimalmodbus
import serial

from pymodbus.client.sync import ModbusSerialClient as ModbusClient

instrument = minimalmodbus.Instrument('/dev/ttyUSB0', 1)
instrument.serial.port = '/dev/ttyUSB0'         # this is the serial port name
instrument.serial.baudrate = 9600        # Baud
instrument.serial.bytesize = 8
instrument.serial.parity   = serial.PARITY_NONE
instrument.serial.stopbits = 1
instrument.serial.timeout  = 0.05          # seconds

instrument.address=1                      # this is the slave address number
instrument.mode = minimalmodbus.MODE_RTU   # rtu or ascii mode
instrument.clear_buffers_before_each_transaction = True
instrument.serial.setRTS(1) #RTS=1,~RTS=0 so ~RE=0,Receive mode enabled for MAX485
instrument.serial.setDTR(1) #DTR=1,~DTR=0 so  DE=0,(In FT232 RTS and DTR pins are inverted)
                   #~RE and DE LED's on USB2SERIAL board will be off

print ('\n    DTR = 1,~DTR = 0 so  DE = 0')
print ('    RTS = 1,~RTS = 0 so ~RE = 0,Receive mode enabled for MAX485')

print ('\n    Waiting for data.....\n')
print(minimalmodbus._get_diagnostic_string())
print("\n")
a=instrument.read_register(4000, 1)
b=a/10
print("total power is",b,' KWh')

a=instrument.read_register(4010, 1)
print("voltage line to line ",a)
frequency=instrument.read_register(4013,1)
print("frequency is",frequency)

print("\n\n\n\n\n\n\n\n\n\n")


RealEnergyTotal=instrument.read_register(1000,1)
print("RealEnergyTotal is ", RealEnergyTotal)
ApparentEnergyTotal=instrument.read_register(1002,1)
print("ApparentEnergyTotal is ", ApparentEnergyTotal)
ReactiveEnergyTotal=instrument.read_register(1004,1)
print("ReactiveEnergyTotal is ", ReactiveEnergyTotal)
RealPowerTotal=instrument.read_register(1006,1)
print("RealPowerTotal is ", RealPowerTotal)
ApparentPowerTotal=instrument.read_register(1008,1)
print("ApparentPowerTotal is ", ApparentPowerTotal)
ReactivePowerTotal=instrument.read_register(1010,1)
print("ReactivePowerTotal is ", ReactivePowerTotal)
PowerFactorTotal=instrument.read_register(1012,1)
print("PowerFactorTotal is ", PowerFactorTotal)
VoltageL_L3PAverage=instrument.read_register(1014,1)
print("VoltageL_L3PAverage is ", VoltageL_L3PAverage)
VoltageL_N3PAverage=instrument.read_register(1016,1)
print("VoltageL_N3PAverage is ", VoltageL_N3PAverage)
Current3PAverage=instrument.read_register(1018,1)
print("Current3PAverage is ", Current3PAverage)
Frequency=instrument.read_register(1020,1)
print("Frequency is ", Frequency)
CurrentA=instrument.read_register(1034,1)
print("CurrentA is ", CurrentA)
CurrentB=instrument.read_register(1036,1)
print("CurrentB is ", CurrentB)
CurrentC=instrument.read_register(1038,1)
print("CurrentC is ", CurrentC)
CurrentN=instrument.read_register(1040,1)
print("CurrentN is ", CurrentN)
VoltageA_B=instrument.read_register(1054,1)
print("VoltageA_B is ", VoltageA_B)
VoltageB_C=instrument.read_register(1056,1)
print("VoltageB_C is ", VoltageB_C)
VoltageC_A=instrument.read_register(1058,1)
print("VoltageC_A is ", VoltageC_A)
VoltageA_N=instrument.read_register(1060,1)
print("VoltageA_N is ", VoltageA_N)
VoltageB_N=instrument.read_register(1062,1)
print("VoltageB_N is ", VoltageB_N)
VoltageC_N=instrument.read_register(1064,1)
print("VoltageC_N is ", VoltageC_N)
RealPowerA=instrument.read_register(1066,1)
print("RealPowerA is ", RealPowerA)
RealPowerB=instrument.read_register(1068,1)
print("RealPowerB is ", RealPowerB)
RealPowerC=instrument.read_register(1070,1)
print("RealPowerC is ", RealPowerC)
ApparentPowerA=instrument.read_register(1072,1)
print("ApparentPowerA is ", ApparentPowerA)
ApparentPowerB=instrument.read_register(1074,1)
print("ApparentPowerB is ", ApparentPowerB)
ApparentPowerC=instrument.read_register(1076,1)
print("ApparentPowerC is ", ApparentPowerC)
ReactivePowerA=instrument.read_register(1078,1)
print("ReactivePowerA is ", ReactivePowerA)
ReactivePowerB=instrument.read_register(1080,1)
print("ReactivePowerB is ", ReactivePowerB)
ReactivePowerC=instrument.read_register(1082,1)
print("ReactivePowerC is ", ReactivePowerC)
CurrentATHD=instrument.read_register(1084,1)
print("CurrentATHD is ", CurrentATHD)
CurrentBTHD=instrument.read_register(1086,1)
print("CurrentBTHD is ", CurrentBTHD)
CurrentCTHD=instrument.read_register(1088,1)
print("CurrentCTHD is ", CurrentCTHD)
VoltageA_NTHD=instrument.read_register(1092,1)
print("VoltageA_NTHD is ", VoltageA_NTHD)
VoltageB_NTHD=instrument.read_register(1094,1)
print("VoltageB_NTHD is ", VoltageB_NTHD)
VoltageC_NTHD=instrument.read_register(1096,1)
print("VoltageC_NTHD is ", VoltageC_NTHD)
VoltageA_BTHD=instrument.read_register(1098,1)
print("VoltageA_BTHD is ", VoltageA_BTHD)
VoltageB_CTHD=instrument.read_register(1100,1)
print("VoltageB_CTHD is ", VoltageB_CTHD)
VoltageC_ATHD=instrument.read_register(1102,1)
print("VoltageC_ATHD is ", VoltageC_ATHD)
RealEnergyTotal=instrument.read_register(4000,1)
print("RealEnergyTotal is ", RealEnergyTotal)
ApparentEnergyTotal=instrument.read_register(4002,1)
print("ApparentEnergyTotal is ", ApparentEnergyTotal)
ReactiveEnergyTotal=instrument.read_register(4004,1)
print("ReactiveEnergyTotal is ", ReactiveEnergyTotal)
RealPowerTotal=instrument.read_register(4006,1)
print("RealPowerTotal is ", RealPowerTotal)
ApparentPowerTotal=instrument.read_register(4007,1)
print("ApparentPowerTotal is ", ApparentPowerTotal)
ReactivePowerTotal=instrument.read_register(4008,1)
print("ReactivePowerTotal is ", ReactivePowerTotal)
PowerFactorTotal=instrument.read_register(4009,1)
print("PowerFactorTotal is ", PowerFactorTotal)
VoltageL_L3P=instrument.read_register(4010,1)
print("VoltageL_L3P is ", VoltageL_L3P)
VoltageL_N3PAverage=instrument.read_register(4011,1)
print("VoltageL_N3PAverage is ", VoltageL_N3PAverage)
Current3PAverage=instrument.read_register(4012,1)
print("Current3PAverage is ", Current3PAverage)
Frequency=instrument.read_register(4013,1)
print("Frequency is ", Frequency)
CurrentA=instrument.read_register(4020,1)
print("CurrentA is ", CurrentA)
CurrentB=instrument.read_register(4021,1)
print("CurrentB is ", CurrentB)
CurrentC=instrument.read_register(4022,1)
print("CurrentC is ", CurrentC)
CurrentN=instrument.read_register(4023,1)
print("CurrentN is ", CurrentN)
VoltageA_B=instrument.read_register(4030,1)
print("VoltageA_B is ", VoltageA_B)
VoltageB_C=instrument.read_register(4031,1)
print("VoltageB_C is ", VoltageB_C)
VoltageC_A=instrument.read_register(4032,1)
print("VoltageC_A is ", VoltageC_A)
VoltageA_N=instrument.read_register(4033,1)
print("VoltageA_N is ", VoltageA_N)
VoltageB_N=instrument.read_register(4034,1)
print("VoltageB_N is ", VoltageB_N)
VoltageC_N=instrument.read_register(4035,1)
print("VoltageC_N is ", VoltageC_N)
RealPowerA=instrument.read_register(4036,1)
print("RealPowerA is ", RealPowerA)
RealPowerB=instrument.read_register(4037,1)
print("RealPowerB is ", RealPowerB)
RealPowerC=instrument.read_register(4038,1)
print("RealPowerC is ", RealPowerC)
ApparentPowerA=instrument.read_register(4039,1)
print("ApparentPowerA is ", ApparentPowerA)
ApparentPowerB=instrument.read_register(4040,1)
print("ApparentPowerB is ", ApparentPowerB)
ApparentPowerC=instrument.read_register(4041,1)
print("ApparentPowerC is ", ApparentPowerC)
ReactivePowerA=instrument.read_register(4042,1)
print("ReactivePowerA is ", ReactivePowerA)
ReactivePowerB=instrument.read_register(4043,1)
print("ReactivePowerB is ", ReactivePowerB)
ReactivePowerC=instrument.read_register(4044,1)
print("ReactivePowerC is ", ReactivePowerC)
CurrentATHD=instrument.read_register(4045,1)
print("CurrentATHD is ", CurrentATHD)
CurrentBTHD=instrument.read_register(4046,1)
print("CurrentBTHD is ", CurrentBTHD)
CurrentCTHD=instrument.read_register(4047,1)
print("CurrentCTHD is ", CurrentCTHD)
PowerFactorTotalSigned=instrument.read_register(4048,1)
print("PowerFactorTotalSigned is ", PowerFactorTotalSigned)
VoltageA_NTHD=instrument.read_register(4049,1)
print("VoltageA_NTHD is ", VoltageA_NTHD)
VoltageB_NTHD=instrument.read_register(4050,1)
print("VoltageB_NTHD is ", VoltageB_NTHD)
VoltageC_NTHD=instrument.read_register(4051,1)
print("VoltageC_NTHD is ", VoltageC_NTHD)
VoltageA_BTHD=instrument.read_register(4052,1)
print("VoltageA_BTHD is ", VoltageA_BTHD)
VoltageB_CTHD=instrument.read_register(4053,1)
print("VoltageB_CTHD is ", VoltageB_CTHD)
VoltageC_ATHD=instrument.read_register(4054,1)
print("VoltageC_ATHD is ", VoltageC_ATHD)




